spring:
  redis:
    host: localhost
    port: 6379

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST}:3306/ordersystem
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show_sql: true

#  eureka용 서비스 이름 명명
#  spring 안에 써야함!
  application:
    name: product-service

logging:
  level:
    root: info
jwt:
  expiration: 30
  secretKey: my_token_secret #변수화한 tokenKey 값
  expirationRt: 14400
  secretKeyRt: hackerton_secret #변수화한 rt 값

# aws s3 설정
cloud:
  aws:
    credentials:
      access-key: xxxx
      secret-key: yyyy
    region:
      static: ap-southeast-2
    s3:
      bucket: jungeun-file


